name: Deploy Course

on:
  workflow_dispatch:
    inputs:
      course-json-path:
        description: 'Path to the course JSON file'
        required: true
        default: 'course_deploy.json'
      # use this for the re-publishing 
      mode:
        description: 'Operation mode: "create" or "update"'
        required: false
        default: 'create'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout current repo
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      # Checkout upload action repo 
      - name: Checkout Upload Action
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: qBraid/upload-course-action
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: .github/actions/upload-action
          
      # Deploy to qbraid using the upload course action
      - name: Deploy to qBraid
        id: deploy
        uses: ./.github/actions/upload-action
        with:
          persist-credentials: false
          # the api key associated with the right organization user
          api-key: ${{ secrets.QBRAID_API_KEY }}

          repo-read-token: ${{ secrets.GH_TOKEN }}
          # input to the path of the course json file which has all the course details and
          # content to be deployed
          course-json-path: ${{ github.event.inputs.course-json-path }}

          # operation mode - create for new course deployment, update for re-publishing an existing course with changes
          mode: ${{ github.event.inputs.mode }}


      - name: Deployment summary
        run: |
          echo "Course: ${{ steps.deploy.outputs.course_name }}"
          echo "Custom ID: ${{ steps.deploy.outputs.course-custom-id }}"
          echo "URL: ${{ steps.deploy.outputs.qbook_url }}"
